### ISSUE TITLE
Trie lookup error: Database missing expected key

### ISSUE THREAD

**Issue by carumusan** [kulupu/kulupu#13]
```Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]: ====================
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]: Version: 0.2.2-d294ede-x86_64-linux-gnu
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]: stack backtrace:
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    0: sp_panic_handler::set::{{closure}}
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    1: std::panicking::rust_panic_with_hook
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libstd/panicking.rs:477
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    2: std::panicking::continue_panic_fmt
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libstd/panicking.rs:380
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    3: rust_begin_unwind
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libstd/panicking.rs:307
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    4: core::panicking::panic_fmt
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libcore/panicking.rs:85
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    5: core::result::unwrap_failed
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libcore/result.rs:1165
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    6: <sp_state_machine::ext::Ext<H,N,B,T> as sp_externalities::Externalities>::storage
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    7: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    8: std::thread::local::LocalKey<T>::with
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:    9: sp_io::storage::get
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   10: <<sc_executor::deprecated_host_interface::SubstrateExternals as sp_wasm_interface::HostFunctions>::host_functions::ext_get_allocated_storage as sp_wasm_interface::Function>::execute
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   11: <sc_executor::wasmi_execution::FunctionExecutor as wasmi::host::Externals>::invoke_index
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   12: wasmi::func::FuncInstance::invoke
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   13: wasmi::runner::Interpreter::start_execution
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   14: wasmi::func::FuncInstance::invoke
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   15: std::thread::local::LocalKey<T>::with
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   16: <sc_executor::wasmi_execution::WasmiRuntime as sc_executor::wasm_runtime::WasmRuntime>::call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   17: std::panicking::try::do_call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   18: __rust_maybe_catch_panic
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libpanic_unwind/lib.rs:80
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   19: sc_executor::native_executor::safe_call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   20: std::thread::local::LocalKey<T>::with
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   21: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   22: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   23: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block,sp_core::hasher::blake2::Blake2Hasher>>::contextual_call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   24: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallRuntimeAt<Block>>::call_api_at
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   25: <kulupu_runtime::RuntimeApiImpl<RuntimeApiImplCall> as sp_api::Core<<kulupu_runtime::Runtime as sp_runtime::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   26: sp_api::Core::initialize_block
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   27: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block,sp_core::hasher::blake2::Blake2Hasher>>::contextual_call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   28: sp_consensus_pow::runtime_decl_for_DifficultyApi::difficulty_call_api_at
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   29: sp_consensus_pow::DifficultyApi::difficulty
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   30: <kulupu_pow::RandomXAlgorithm<C> as sc_consensus_pow::PowAlgorithm<B>>::difficulty
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   31: <sc_consensus_pow::PowVerifier<B,C,S,Algorithm> as sp_consensus::import_queue::Verifier<B>>::verify
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   32: sp_consensus::import_queue::import_single_block
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   33: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   34: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   35: futures_executor::thread_pool::PoolState::work
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   36: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   37: std::panicking::try::do_call
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   38: __rust_maybe_catch_panic
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libpanic_unwind/lib.rs:80
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   39: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:       std::sys_common::thread::start_thread
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libstd/sys_common/thread.rs:13
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:       std::sys::unix::thread::Thread::new::thread_start
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:              at src/libstd/sys/unix/thread.rs:79
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   42: start_thread
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:   43: __clone
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]: Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x057831426385642acdb224a2c0a71f16a4aacbf43b958077035158e40fb741fd"', src/libcore/result.rs:1165
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]: This is a bug. Please report it at:
Dec 17 05:16:51 bm-upbeat-robinson kulupu[82996]:         https://github.com/kulupu/kulupu/issues
```

**Comment by sorpaas** [comment]
Should have been fixed with v1.0.0.
