### ISSUE TITLE
Reported mining hashrate drop in v2.8.0 and v2.8.1

### ISSUE THREAD

**Issue by sorpaas** [kulupu/kulupu#164]
We're still gathering data. If you are experiencing the issue, please post:

* Your system config.
* Logs of the Kulupu node.
* You expected hashrate (what were you seeing on v2.7.0?)
* Node build method (did you use the release build or did you build your node yourself, and if the latter, what Rust version did you use?)

**Comment by hieixu** [comment]
amd 5950X with 32G *4
hashrate should be 13.5K
I think this cause by outdate nodes. 
mining will stop when it get new block from outdate node.
logs here:
2021-10-05 22:08:39 Local hashrate: 11966 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:41 Local hashrate: 11957 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:42 💤 Idle (47 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 5.0kiB/s ⬆ 11.2kiB/s
2021-10-05 22:08:43 Local hashrate: 11975 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:46 Local hashrate: 11993 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:47 ⚙️  Syncing  0.0 bps, target=#728235 (48 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 4.7kiB/s ⬆ 6.1kiB/s
2021-10-05 22:08:48 Local hashrate: 11984 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:49 panicked at 'Storage root must match that calculated.', /rustbuilder/.cargo/git/checkouts/substrate-7e08433d4c370a21/3e96c69/frame/executive/src/lib.rs:455:9
2021-10-05 22:08:49 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Wasmi(Trap(Trap { kind: Unreachable })))))
2021-10-05 22:08:49 💔 Error importing block 0xd1147d7fbe86e1d2188af855d28e3f5e305db115184f81f83c4a10a641671690: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))")))
2021-10-05 22:08:50 Local hashrate: 12000 H/s, network hashrate: 876251 H/s, expected one block every 1h 13m (73 blocks)
2021-10-05 22:08:52 ⚙️  Syncing  0.0 bps, target=#728235 (48 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 80.9kiB/s ⬆ 20.5kiB/s
2021-10-05 22:08:52 Local hashrate: 12019 H/s, network hashrate: 876251 H/s, expected one block every 1h 12m (72 blocks)
2021-10-05 22:08:57 💤 Idle (47 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 3.9kiB/s ⬆ 6.4kiB/s
2021-10-05 22:09:01 🙌 Starting consensus session on top of parent 0x914dd4d8489d0cacfec397f014b59e10fe2739aaa4395859ce7060aadb3264b7
2021-10-05 22:09:01 🎁 Prepared block for proposing at 727972 [hash: 0x873911b42d8cbe42cfe719ae56d11ac2743c6f39506a9e258d6cefa685b8bbb4; parent_hash: 0x914d…64b7; extrinsics (1): [0x99a5…633c]]
2021-10-05 22:09:02 💤 Idle (47 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 2.5kiB/s ⬆ 4.9kiB/s
2021-10-05 22:09:03 Local hashrate: 11739 H/s, network hashrate: 876251 H/s, expected one block every 1h 14m (74 blocks)
2021-10-05 22:09:05 Local hashrate: 11757 H/s, network hashrate: 876251 H/s, expected one block every 1h 14m (74 blocks)
2021-10-05 22:09:07 ⚙️  Syncing  0.0 bps, target=#728235 (48 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 1.2kiB/s ⬆ 1.2kiB/s
2021-10-05 22:09:08 Local hashrate: 11775 H/s, network hashrate: 876251 H/s, expected one block every 1h 14m (74 blocks)
2021-10-05 22:09:10 Local hashrate: 11768 H/s, network hashrate: 876251 H/s, expected one block every 1h 14m (74 blocks)
2021-10-05 22:09:12 ⚙️  Syncing  0.0 bps, target=#728235 (48 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 2.8kiB/s ⬆ 3.2kiB/s
2021-10-05 22:09:12 Local hashrate: 11794 H/s, network hashrate: 876251 H/s, expected one block every 1h 14m (74 blocks)
2021-10-05 22:09:17 ⚙️  Syncing  0.0 bps, target=#728235 (48 peers), best: #727971 (0x914d…64b7), finalized #0 (0xf7a9…69ba), ⬇ 3.6kiB/s ⬆ 4.1kiB/s
2021-10-05 22:09:19 panicked at 'Storage root must match that calculated.', /rustbuilder/.cargo/git/checkouts/substrate-7e08433d4c370a21/3e96c69/frame/executive/src/lib.rs:455:9
2021-10-05 22:09:19 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Wasmi(Trap(Trap { kind: Unreachable })))))
2021-10-05 22:09:19 💔 Error importing block 0xd1147d7fbe86e1d2188af855d28e3f5e305db115184f81f83c4a10a641671690: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))")))
2021-10-05 22:09:22 ⚙️  Syncing  0.2 bps, target=#728235 (48 peers), best: #727972 (0x4229…e9a2), finalized #0 (0xf7a9…69ba), ⬇ 23.2kiB/s ⬆ 5.3kiB/s
2021-10-05 22:09:27 💤 Idle (47 peers), best: #727972 (0x4229…e9a2), finalized #0 (0xf7a9…69ba), ⬇ 3.7kiB/s ⬆ 12.7kiB/s
2021-10-05 22:09:31 🙌 Starting consensus session on top of parent 0x4229a4230d1a67f2822a7963f5e9685f772f551166ff92e4cb42112ad484e9a2
2021-10-05 22:09:31 🎁 Prepared block for proposing at 727973 [hash: 0xe98b310094f63fd58617423d9cb9de4e32a53e9e89442523eb7a876aacbef28d; parent_hash: 0x4229…e9a2; extrinsics (1): [0x4e1f…dd0c]]
2021-10-05 22:09:32 💤 Idle (47 peers), best: #727972 (0x4229…e9a2), finalized #0 (0xf7a9…69ba), ⬇ 2.1kiB/s ⬆ 3.0kiB/s
2021-10-05 22:09:33 Local hashrate: 11309 H/s, network hashrate: 886437 H/s, expected one block every 1h 18m (78 blocks)
2021-10-05 22:09:35 Operation not permitted (os error 1)

**Comment by cryptechuk** [comment]
threadripper 3990x  getting speeds of  2900 h/s 

when mining with v2.7.0  I was getting around 39000 h/s.  Even that's was quite slow compared non kulupu randomx with speeds of  52000 h/s

ubuntu 20.04


![kulupu1](https://user-images.githubusercontent.com/40968667/136187264-11fb64d9-e2bd-4a2a-9425-aad9a43ef639.png)
  

![kulupu2](https://user-images.githubusercontent.com/40968667/136187664-faea7a46-9f77-41be-8620-e18f5b862b99.jpg)

**Comment by cryptechuk** [comment]
Any updates for a fix on miner?   seems to be a big memory leak
