### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by majordutch** [kulupu/kulupu#2]
When trying to sync in a network that appears to have unexpectedly forked, the following exception occurs when connected to a node on a (presumed) different fork.

```
Hash: given=eb93fc5d6d23f3234ea96afccf4edbe79d03f4f430391d478ad21c925d2940ff, expected=0fecae97d6e00d780db7a030295cc50b8d3c6536de3aaf868fc0fe780ab5053f

====================

Version: 0.1.0-4e3ae8a-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: kulupu_runtime::api::dispatch
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
   7: std::thread::local::LocalKey<T>::with
   8: <kulupu::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
   9: <substrate_executor::native_executor::NativeExecutor<D> as substrate_primitives::traits::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call
  10: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
  11: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_call_with_native_else_wasm_strategy
  12: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
  13: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  14: substrate_client::client::Client<B,E,Block,RA>::apply_block
  15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  16: <alloc::sync::Arc<T> as substrate_consensus_common::block_import::BlockImport<B>>::import_block
  17: substrate_consensus_common::import_queue::import_single_block
  18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  19: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: futures_executor::thread_pool::PoolState::work
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  28: start_thread
  29: __clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', vendor/substrate/srml/executive/src/lib.rs:271

This is a bug. Please report it at:

        https://github.com/kulupu/kulupu/issues

Hash not equal
eb93fc5d6d23f3234ea96afccf4edbe79d03f4f430391d478ad21c925d2940ff
0fecae97d6e00d780db7a030295cc50b8d3c6536de3aaf868fc0fe780ab5053f
panicked at 'Storage root must match that calculated.', /home/sorpaas/repos/kulupu/vendor/substrate/srml/executive/src/lib.rs:271:3
```

**Comment by sorpaas** [comment]
Should have been fixed now as we upgraded Substrate!
