### ISSUE TITLE
panic: Timestamp must increment by at least <MinimumPeriod> between sequential blocks

### ISSUE THREAD

**Issue by soc1c** [kulupu/kulupu#3]
```
2019-09-22 20:40:07 Kulupu
2019-09-22 20:40:07   version 0.1.0-4e3ae8a-x86_64-linux-gnu
2019-09-22 20:40:07   by Wei Tang <hi@that.world>, 2017, 2018
2019-09-22 20:40:07 Chain specification: Kulupu
2019-09-22 20:40:07 Node name: elfin-eyes-2365
2019-09-22 20:40:07 Roles: AUTHORITY
2019-09-22 20:40:07 Highest known block at #628
2019-09-22 20:40:07 Local node identity is: QmVcWNnWhQJkFdU7qr2SJJED1GS3Jhh6ojtQDDEo84o7Ev
2019-09-22 20:40:07 Starting consensus session on top of parent 0x87801c91818fcee6592bf05a5cf5463b002eb05bbad2af1355864b0a34dedb07
2019-09-22 20:40:07 Prepared block for proposing at 629 [hash: 0xf45a23c3758fc09c2e1a578a9a0bfbc551b104e9b7735d6bd3fa0cdc4b472766; parent_hash: 0x8780…db07; extrinsics: [0xce9f…dffb, 0x2df1…e0d8]]
2019-09-22 20:40:07 Next block's difficulty: Ok(Difficulty(328))
2019-09-22 20:40:08 Discovered new external address for our node: /ip4/84.160.81.78/tcp/30333/p2p/QmVcWNnWhQJkFdU7qr2SJJED1GS3Jhh6ojtQDDEo84o7Ev
2019-09-22 20:40:12 Next block's difficulty: Ok(Difficulty(328))
2019-09-22 20:40:12 Verification failed from peer: PoW validation error: invalid seal
2019-09-22 20:40:12 Idle (0 peers), best: #628 (0x8780…db07), finalized #0 (0x8568…b4f3), ⬇ 21.8kiB/s ⬆ 4.6kiB/s
2019-09-22 20:40:17 Idle (0 peers), best: #628 (0x8780…db07), finalized #0 (0x8568…b4f3), ⬇ 10.7kiB/s ⬆ 5.2kiB/s
2019-09-22 20:40:20 Next block's difficulty: Ok(Difficulty(328))

====================

Version: 0.1.0-4e3ae8a-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic
   3: <srml_timestamp::Call<T> as sr_primitives::traits::Dispatchable>::dispatch
   4: <kulupu_runtime::Call as sr_primitives::traits::Dispatchable>::dispatch
   5: <sr_primitives::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sr_primitives::traits::Applyable>::apply
   6: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::apply_extrinsic_with_len
   7: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   8: kulupu_runtime::api::dispatch
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  11: std::thread::local::LocalKey<T>::with
  12: <kulupu::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
  13: <substrate_executor::native_executor::NativeExecutor<D> as substrate_primitives::traits::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call
  14: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
  15: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_call_with_native_else_wasm_strategy
  16: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
  17: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  18: substrate_client::client::Client<B,E,Block,RA>::apply_block
  19: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  20: <alloc::sync::Arc<T> as substrate_consensus_common::block_import::BlockImport<B>>::import_block
  21: substrate_consensus_common::import_queue::import_single_block
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: futures_executor::thread_pool::PoolState::work
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  31: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  32: start_thread
  33: __clone


Thread 'import-queue-worker-0' panicked at 'Timestamp must increment by at least <MinimumPeriod> between sequential blocks', vendor/substrate/srml/timestamp/src/lib.rs:228

This is a bug. Please report it at:

	https://github.com/kulupu/kulupu/issues

panicked at 'Timestamp must increment by at least <MinimumPeriod> between sequential blocks', /home/sorpaas/repos/kulupu/vendor/substrate/srml/timestamp/src/lib.rs:228:4
2019-09-22 20:40:21 Block import error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2019-09-22 20:40:22 Syncing  0.0 bps, target=#687 (1 peers), best: #628 (0x8780…db07), finalized #0 (0x8568…b4f3), ⬇ 14.4kiB/s ⬆ 4.8kiB/s
2019-09-22 20:40:23 Next block's difficulty: Ok(Difficulty(328))

====================

Version: 0.1.0-4e3ae8a-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic
   3: <srml_timestamp::Call<T> as sr_primitives::traits::Dispatchable>::dispatch
   4: <kulupu_runtime::Call as sr_primitives::traits::Dispatchable>::dispatch
   5: <sr_primitives::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sr_primitives::traits::Applyable>::apply
   6: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::apply_extrinsic_with_len
   7: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   8: kulupu_runtime::api::dispatch
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  11: std::thread::local::LocalKey<T>::with
  12: <kulupu::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
  13: <substrate_executor::native_executor::NativeExecutor<D> as substrate_primitives::traits::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call
  14: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
  15: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_call_with_native_else_wasm_strategy
  16: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
  17: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  18: substrate_client::client::Client<B,E,Block,RA>::apply_block
  19: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  20: <alloc::sync::Arc<T> as substrate_consensus_common::block_import::BlockImport<B>>::import_block
  21: substrate_consensus_common::import_queue::import_single_block
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: futures_executor::thread_pool::PoolState::work
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  31: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  32: start_thread
  33: __clone


Thread 'import-queue-worker-0' panicked at 'Timestamp must increment by at least <MinimumPeriod> between sequential blocks', vendor/substrate/srml/timestamp/src/lib.rs:228

This is a bug. Please report it at:

	https://github.com/kulupu/kulupu/issues

panicked at 'Timestamp must increment by at least <MinimumPeriod> between sequential blocks', /home/sorpaas/repos/kulupu/vendor/substrate/srml/timestamp/src/lib.rs:228:4
2019-09-22 20:40:25 Block import error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2019-09-22 20:40:26 Discovered new external address for our node: /ip4/192.168.161.11/tcp/30333/p2p/QmVcWNnWhQJkFdU7qr2SJJED1GS3Jhh6ojtQDDEo84o7Ev
2019-09-22 20:40:27 Next block's difficulty: Ok(Difficulty(328))
2019-09-22 20:40:27 Idle (1 peers), best: #628 (0x8780…db07), finalized #0 (0x8568…b4f3), ⬇ 20.0kiB/s ⬆ 8.9kiB/s
```

**Comment by sorpaas** [comment]
This is now a proper error instead of a panic. So the issue should be fixed!
