### ISSUE TITLE
Thread 'main' panicked at 'Invalid author version', src\service.rs:50

### ISSUE THREAD

**Issue by AlvinDINGapore** [kulupu/kulupu#83]
Any ideas guys? i5-9600K WIN10 x64 nothing special normal PC.

C:\kulupu>kulupu.exe --validator --author [removed for bug post] --threads 6
2020-09-15 13:32:38.390 main WARN sc_network::config  🙇 You are using the peer ID QmU2WrqoJWWqrhUvk98SBvVbtUCqVcrXhPG7yftecyXnGw. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-09-15 13:32:38.394 main INFO sc_cli::runner  Kulupu
2020-09-15 13:32:38.395 main INFO sc_cli::runner  ✌️  version 2.1.0-8eade86-x86_64-windows-msvc
2020-09-15 13:32:38.395 main INFO sc_cli::runner  ❤️  by Wei Tang <wei@that.world>, 2019-2020
2020-09-15 13:32:38.395 main INFO sc_cli::runner  📋 Chain specification: Kulupu
2020-09-15 13:32:38.395 main INFO sc_cli::runner  🏷  Node name: nimble-locket-2620
2020-09-15 13:32:38.395 main INFO sc_cli::runner  👤 Role: AUTHORITY
2020-09-15 13:32:38.395 main INFO sc_cli::runner  💾 Database: RocksDb at C:\Users\imk\AppData\Local\kulupu.exe\data\chains\kulupu\db
2020-09-15 13:32:38.395 main INFO sc_cli::runner  ⛓  Native runtime: kulupu-9 (kulupu-0.tx6.au5)

====================

Version: 2.1.0-8eade86-x86_64-windows-msvc

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: BaseThreadInitThunk
  16: RtlUserThreadStart

Thread 'main' panicked at 'Invalid author version', src\service.rs:50

This is a bug. Please report it at:

        https://github.com/kulupu/kulupu/issues

C:\kulupu>

**Comment by kristiantow007** [comment]
same issue with amd a6

**Comment by sgaragagghu** [comment]
@AlvinDINGapore @kristiantow007 i think you just wrote a wrong address.
https://kulupu.subscan.io/tools/ss58_transform
insert here your address and copy you corresponding kulupu address or public key into the miner start command

**Comment by kristiantow007** [comment]
Thank you for the help sir, but after trying public address my cmd its auto close when I try to run my start command
what happen sir ?

**Comment by kristiantow007** [comment]
@sgaragagghu nvm, that was work fine thanks sir
btw how to check my kulupu balance with public key as a wallet ?

**Comment by sgaragagghu** [comment]
> @sgaragagghu nvm, that was work fine thanks sir
> btw how to check my kulupu balance with public key as a wallet ?

https://kulupu.subscan.io/tools/ss58_transform

**Comment by sorpaas** [comment]
This is due to invalid author address. I think it has been clarified above how to generate correct addresses. Closing.
