### ISSUE TITLE
panicked at 'division by zero'

### ISSUE THREAD

**Issue by cocakuma** [kulupu/kulupu#90]
Version: 2.2.0-cfc3339-x86_64-windows-msvc

 ```
  0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: BaseThreadInitThunk
  12: RtlUserThreadStart
```

Thread` '<unnamed>' `panicked at 'division by zero', C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\primitive-types-0.7.2\src\lib.rs:32

**Comment by olljanat** [comment]
Happened for me on Linux too.

Here is lot with bit more details:
```
2021-01-11 08:12:22  ⚙  Syncing  4.2 bps, target=#352493 (12 peers), best: #352350 (0x8b45…efc1), finalized #0 (0xf7a9…69ba), ⬇ 2.0kiB/s ⬆ 2.5kiB/s    
2021-01-11 08:12:27  ⚙  Syncing  4.6 bps, target=#352493 (13 peers), best: #352373 (0xc0fb…77c7), finalized #0 (0xf7a9…69ba), ⬇ 3.3kiB/s ⬆ 3.7kiB/s    
2021-01-11 08:12:30  At block boundary, generating new RandomX light cache with key hash 0x4f87…ec0a ...    
2021-01-11 08:12:32  💤 Idle (12 peers), best: #352384 (0xfc0f…ac6b), finalized #0 (0xf7a9…69ba), ⬇ 9.0kiB/s ⬆ 1.3kiB/s    
2021-01-11 08:12:33  🙌 Starting consensus session on top of parent 0xdc1d22d994a6030863f2ebae5076f284a0d8fbdd0341b75767a1cf1af3a7cab5    
2021-01-11 08:12:34  Timeout fired waiting for transaction pool at block #352399. Proceeding with production.    
2021-01-11 08:12:34  🎁 Prepared block for proposing at 352400 [hash: 0xd5223b34f1c846384fc64373c21af1cc427482d033ed549256de23b2732e613b; parent_hash: 0xdc1d…cab5; extrinsics (2): [0x8c31…ec88, 0x7537…20ef]]    
2021-01-11 08:12:35  At block boundary, generating new RandomX full cache with key hash 0x4f87…ec0a ...    
2021-01-11 08:12:37  💤 Idle (12 peers), best: #352455 (0xf254…8881), finalized #0 (0xf7a9…69ba), ⬇ 1.8kiB/s ⬆ 1.9kiB/s    
2021-01-11 08:12:40  🙌 Starting consensus session on top of parent 0xcd71cace5a82260926e468bb1be66eb9f1f2a044f8c2e667454cc2f6444e7ef8    
2021-01-11 08:12:40  🎁 Prepared block for proposing at 352495 [hash: 0x75bcfda25c345549435c256109b8be753151071b0146f1f2241f851ef7d178de; parent_hash: 0xcd71…7ef8; extrinsics (2): [0xeac0…b11f, 0x7537…20ef]]    
2021-01-11 08:13:06  🙌 Starting consensus session on top of parent 0x8002fe74fb08a0316908599d37fe2013718a14f7592b712f7320e7119120c1a4    
2021-01-11 08:13:06  🎁 Prepared block for proposing at 352496 [hash: 0xa99061b4e9c6b9738a63fd67dd3f7db9ad0d627467527a3ddc36946dcf6d6007; parent_hash: 0x8002…c1a4; extrinsics (2): [0x92f6…d721, 0x7537…20ef]]    

====================

Version: 2.4.0-9dc2121-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: primitive_types::U256::div_mod
   6: kulupu_pow::mine
   7: kulupu::service::new_full::{{closure}}
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87:17
  11: start_thread
  12: clone


Thread '<unnamed>' panicked at 'division by zero', /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.7.3/src/lib.rs:38
```
