### ISSUE TITLE
Thread '<unnamed>' panicked at 'division by zero' (v2.3.0, Ubuntu 20.04)

### ISSUE THREAD

**Issue by Shekelme** [kulupu/kulupu#98]
Ubuntu 20.04.1 LTS

```
====================

Version: 2.3.0-f10adb9-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:490:17
   2: std::panicking::begin_panic
   3: primitive_types::U256::div_mod
   4: kulupu_pow::mine
   5: kulupu::service::new_full::{{closure}}
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
   8: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/sys/unix/thread.rs:87:17
   9: start_thread
  10: clone


Thread '<unnamed>' panicked at 'division by zero', /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.7.2/src/lib.rs:32

This is a bug. Please report it at:

        https://github.com/kulupu/kulupu/issues
```
So here I am.

**Comment by dbpatty** [comment]
I had the same problem.
